Linux-888 -> 6.14.2

diff --git a/linux-888/PKGBUILD b/linux-888/PKGBUILD
--- a/linux-888/PKGBUILD
+++ b/linux-888/PKGBUILD
@@ -1,8 +1,8 @@
 pkgbase="linux-888"
 _major=6.14
-_minor=0
+_minor=2
 pkgver=${_major}.${_minor}
-_stable=${_major}
+_stable=${_major}.${_minor}
 _srcname=linux-${_stable}
 pkgdesc='A kernel based on linux-cachyos-bore-lto'
 pkgrel=1
@@ -30,6 +30,7 @@ _cfgsource="https://raw.githubusercontent.com/CachyOS/linux-cachyos/master"
 _patchsource="https://raw.githubusercontent.com/cachyos/kernel-patches/master/${_major}"
 source=(
     "https://cdn.kernel.org/pub/linux/kernel/v${pkgver%%.*}.x/${_srcname}.tar.xz"
+    "${_cfgsource}/linux-cachyos-bore/config"
     "${_cfgsource}/linux-cachyos-bore/auto-cpu-optimization.sh"
     "${_patchsource}/all/0001-cachyos-base-all.patch"
     "${_patchsource}/sched/0001-bore-cachy.patch"
@@ -72,7 +73,7 @@ prepare() {
   done
 
   echo "Setting config..."
-  yes "" | make "${BUILD_FLAGS[@]}" localmodconfig >/dev/null
+  cp ../config .config
 
   chmod +x "${srcdir}"/auto-cpu-optimization.sh
   "${srcdir}"/auto-cpu-optimization.sh
@@ -84,7 +85,7 @@ prepare() {
   scripts/config -e LTO_CLANG_THIN
 
   scripts/config -d HZ_300 \
-            -e "HZ_1000" \
+            -e HZ_1000 \
             --set-val HZ "1000"
 
   scripts/config -d CPU_FREQ_DEFAULT_GOV_SCHEDUTIL \
@@ -92,7 +93,6 @@ prepare() {
 
   scripts/config -d HZ_PERIODIC \
             -d NO_HZ_IDLE \
-            -e NO_HZ_FULL_NODEF \
             -e NO_HZ_FULL \
             -e NO_HZ \
             -e NO_HZ_COMMON \
@@ -107,375 +107,146 @@ prepare() {
   scripts/config -d CC_OPTIMIZE_FOR_PERFORMANCE \
             -e CC_OPTIMIZE_FOR_PERFORMANCE_O3
 
-  scripts/config -m TCP_CONG_CUBIC \
-            -e TCP_CONG_BBR \
-            -e DEFAULT_BBR \
-            --set-str DEFAULT_TCP_CONG bbr \
-            -m NET_SCH_FQ_CODEL \
-            -e NET_SCH_FQ \
-            -d DEFAULT_FQ_CODEL \
-            -e DEFAULT_FQ \
-            -d TCP_CONG_BIC \
-            -d TCP_CONG_WESTWOOD \
-            -d TCP_CONG_HTCP \
-            -d TCP_CONG_HSTCP \
-            -d TCP_CONG_HYBLA \
-            -d TCP_CONG_VEGAS \
-            -d TCP_CONG_NV \
-            -d TCP_CONG_SCALABLE \
-            -d TCP_CONG_LP \
-            -d TCP_CONG_VENO \
-            -d TCP_CONG_YEAH \
-            -d TCP_CONG_ILLINOIS \
-            -d TCP_CONG_DCTCP \
-            -d TCP_CONG_CDG \
-            -d NET_SCH_HFSC \
-            -d NET_SCH_PRIO \
-            -d NET_SCH_MULTIQ \
-            -d NET_SCH_RED \
-            -d NET_SCH_SFB \
-            -d NET_SCH_SFQ \
-            -d NET_SCH_TEQL \
-            -d NET_SCH_TBF \
-            -d NET_SCH_CBS \
-            -d NET_SCH_ETF \
-            -d NET_SCH_TAPRIO \
-            -d NET_SCH_GRED \
-            -d NET_SCH_NETEM \
-            -d NET_SCH_DRR \
-            -d NET_SCH_MQPRIO \
-            -d NET_SCH_SKBPRIO \
-            -d NET_SCH_CHOKE \
-            -d NET_SCH_QFQ \
-            -d NET_SCH_CODEL \
-            -d NET_SCH_HHF \
-            -d NET_SCH_PIE \
-            -d NET_SCH_INGRESS \
-            -d NET_SCH_PLUG \
-            -d NET_SCH_ETS
-
   scripts/config -d TRANSPARENT_HUGEPAGE_MADVISE \
             -e TRANSPARENT_HUGEPAGE_ALWAYS
 
   scripts/config -e USER_NS
 
-  # Additions
-  # Base
-  scripts/config -e XFRM \
-              -m XFRM_ALGO \
-              -m XFRM_USER \
-              -e XFRM_SUB_POLICY \
-              -e XFRM_MIGRATE \
-              -e XFRM_STATISTICS \
-              -m NET_IP_TUNNEL \
-              -m NET_UDP_TUNNEL \
-              -m NF_CONNTRACK \
-              -m NF_LOG_SYSLOG \
-              -e NF_CONNTRACK_MARK \
-              -e NF_CONNTRACK_SECMARK \
-              -e NF_CONNTRACK_ZONES \
-              -e NF_CONNTRACK_PROCFS \
-              -e NF_CONNTRACK_EVENTS \
-              -e NF_CONNTRACK_TIMEOUT \
-              -e NF_CONNTRACK_TIMESTAMP \
-              -e NF_CONNTRACK_LABELS \
-              -e NF_CT_PROTO_DCCP \
-              -e NF_CT_PROTO_SCTP \
-              -e NF_CT_PROTO_UDPLITE \
-              -m NF_NAT \
-              -e NF_NAT_MASQUERADE \
-              -m NFT_CT \
-              -m NFT_MASQ \
-              -m NFT_NAT \
-              -m NFT_REJECT \
-              -m NFT_REJECT_INET \
-              -m NFT_COMPAT \
-              -m NETFILTER_XT_SET \
-              -m NETFILTER_XT_TARGET_LOG \
-              -m NETFILTER_XT_NAT \
-              -m NETFILTER_XT_TARGET_MASQUERADE \
-              -m NETFILTER_XT_MATCH_ADDRTYPE \
-              -m NETFILTER_XT_MATCH_CONNTRACK \
-              -m NETFILTER_XT_MATCH_HL \
-              -m NETFILTER_XT_MATCH_LIMIT \
-              -m NETFILTER_XT_MATCH_RECENT \
-              -m IP_SET \
-              -m NF_DEFRAG_IPV4 \
-              -m NFT_REJECT_IPV4 \
-              -m NF_REJECT_IPV4 \
-              -m IP_NF_IPTABLES \
-              -m IP_NF_FILTER \
-              -m IP_NF_TARGET_REJECT \
-              -m IP_NF_NAT \
-              -m NFT_COMPAT_ARP \
-              -m IP6_NF_IPTABLES_LEGACY \
-              -m NFT_REJECT_IPV6 \
-              -m NF_REJECT_IPV6 \
-              -m NF_LOG_IPV6 \
-              -m IP6_NF_IPTABLES \
-              -m IP6_NF_MATCH_RT \
-              -m IP6_NF_FILTER \
-              -m IP6_NF_NAT \
-              -m NF_DEFRAG_IPV6 \
-              -m STP \
-              -m BRIDGE \
-              -e BRIDGE_IGMP_SNOOPING \
-              -e BRIDGE_MRP \
-              -e BRIDGE_CFM \
-              -m LLC \
-              -m NET_CLS_U32 \
-              -e CLS_U32_PERF \
-              -e CLS_U32_MARK \
-              -m NET_ACT_CSUM \
-              -e GRO_CELLS \
-              -m NET_SELFTESTS \
-              -m ENCLOSURE_SERVICES \
-              -m SCSI_ENCLOSURE \
-              -m SCSI_SAS_ATTRS \
-              -m MII \
-              -m WIREGUARD \
-              -m TUN \
-              -m PHYLIB \
-              -e SWPHY \
-              -e LED_TRIGGER_PHY \
-              -m FIXED_PHY \
-              -m MDIO_DEVICE \
-              -m MDIO_BUS \
-              -m FWNODE_MDIO \
-              -m ACPI_MDIO \
-              -m MDIO_DEVRES \
-              -m USB_NET_DRIVERS \
-              -m USB_RTL8152 \
-              -m USB_USBNET \
-              -m USB_NET_CDCETHER \
-              -m USB_RTL8153_ECM \
-              -m USB_STORAGE \
-              -m USB_UAS \
-              -m APPLE_MFI_FASTCHARGE \
-              -m XFS_FS \
-              -e XFS_SUPPORT_V4 \
-              -e XFS_SUPPORT_ASCII_CI \
-              -e XFS_POSIX_ACL \
-              -e XFS_RT \
-              -e XFS_DRAIN_INTENTS \
-              -e XFS_LIVE_HOOKS \
-              -e XFS_MEMORY_BUFS \
-              -e XFS_BTREE_IN_MEM \
-              -e XFS_ONLINE_SCRUB \
-              -e XFS_ONLINE_REPAIR \
-              -m OVERLAY_FS \
-              -e OVERLAY_FS_REDIRECT_DIR \
-              -e OVERLAY_FS_INDEX \
-              -e OVERLAY_FS_XINO_AUTO \
-              -e OVERLAY_FS_METACOPY \
-              -m NTFS3_FS \
-              -e NTFS3_LZX_XPRESS \
-              -e NTFS3_FS_POSIX_ACL \
-              -e SECURITY_NETWORK_XFRM \
-              -m CRYPTO_CURVE25519_X86 \
-              -m CRYPTO_CHACHA20_X86_64 \
-              -m CRYPTO_POLY1305_X86_64 \
-              -m CRYPTO_ARCH_HAVE_LIB_CHACHA \
-              -m CRYPTO_LIB_CHACHA_GENERIC \
-              -m CRYPTO_LIB_CHACHA \
-              -m CRYPTO_ARCH_HAVE_LIB_CURVE25519 \
-              -m CRYPTO_LIB_CURVE25519_GENERIC \
-              -m CRYPTO_LIB_CURVE25519 \
-              -m CRYPTO_ARCH_HAVE_LIB_POLY1305 \
-              -m CRYPTO_LIB_POLY1305_GENERIC \
-              -m CRYPTO_LIB_POLY1305 \
-              -m CRYPTO_LIB_CHACHA20POLY1305 \
-              -e NETFILTER_FAMILY_ARP \
-              -m NF_TABLES \
-              -e NF_TABLES_INET \
-              -e NF_TABLES_NETDEV \
-              -m NFT_CT \
-              -m NFT_MASQ \
-              -m NFT_NAT \
-              -m NFT_REJECT \
-              -m NFT_REJECT_INET \
-              -m NFT_COMPAT \
-              -e NF_TABLES_IPV4 \
-              -m NFT_REJECT_IPV4 \
-              -e NF_TABLES_ARP \
-              -m NFT_COMPAT_ARP \
-              -e NF_TABLES_IPV6 \
-              -m NFT_REJECT_IPV6 \
-              -m SND_RAWMIDI \
-              -m SND_UMP \
-              -e SND_UMP_LEGACY_RAWMIDI \
-              -m SND_SEQ_MIDI_EVENT \
-              -m SND_SEQ_MIDI \
-              -m SND_SEQ_UMP_CLIENT \
-              -m SND_USB_AUDIO \
-              -e SND_USB_AUDIO_MIDI_V2 \
-              -e SND_USB_AUDIO_USE_MEDIA_CONTROLLER \
-              -m SND_USB_UA101 \
-              -m SND_USB_USX2Y \
-              -m SND_USB_US122L \
-              -m CRYPTO_DEFLATE \
-              -m CRYPTO_842 \
-              -m CRYPTO_LZ4 \
-              -m CRYPTO_LZ4HC \
-              -m THINKPAD_ACPI \
-              -m DM_INTEGRITY \
-              -m HW_RANDOM_INTEL \
-              -m HW_RANDOM_AMD \
-              -m HID_LOGITECH_DJ \
-              -e HID_BPF \
-              -e LOGITECH_FF \
-              -e LOGIRUMBLEPAD2_FF \
-              -e LOGIG940_FF \
-              -e LOGIWHEELS_FF
+  # Logs
+  DEBUG_LOG="debug_kernel_cfg.log"
 
-  # x86_64 cryptos
-  scripts/config -m CRYPTO_BLOWFISH_X86_64 \
-              -m CRYPTO_CAMELLIA_X86_64 \
-              -m CRYPTO_CAMELLIA_AESNI_AVX_X86_64 \
-              -m CRYPTO_CAMELLIA_AESNI_AVX2_X86_64 \
-              -m CRYPTO_CAST5_AVX_X86_64 \
-              -m CRYPTO_CAST6_AVX_X86_64 \
-              -m CRYPTO_DES3_EDE_X86_64 \
-              -m CRYPTO_SERPENT_SSE2_X86_64 \
-              -m CRYPTO_SERPENT_AVX_X86_64 \
-              -m CRYPTO_SERPENT_AVX2_X86_64 \
-              -m CRYPTO_SM4_AESNI_AVX_X86_64 \
-              -m CRYPTO_SM4_AESNI_AVX2_X86_64 \
-              -m CRYPTO_TWOFISH_X86_64 \
-              -m CRYPTO_TWOFISH_X86_64_3WAY \
-              -m CRYPTO_TWOFISH_AVX_X86_64 \
-              -m CRYPTO_ARIA_AESNI_AVX_X86_64 \
-              -m CRYPTO_ARIA_AESNI_AVX2_X86_64 \
-              -m CRYPTO_ARIA_GFNI_AVX512_X86_64 \
-              -m CRYPTO_AEGIS128_AESNI_SSE2 \
-              -m CRYPTO_NHPOLY1305_SSE2 \
-              -m CRYPTO_NHPOLY1305_AVX2 \
-              -m CRYPTO_SM3_AVX_X86_64
+  # Helper functions
+  disable_config_pattern() {
+    local pattern="$1"
+    
+    echo "======================================" >> "$DEBUG_LOG"
+    echo "Disabling pattern: $pattern" >> "$DEBUG_LOG"
+    echo "======================================" >> "$DEBUG_LOG"
+    
+    grep -E "^CONFIG_$pattern=[ym]" .config | while IFS= read -r line; do
+      key=$(echo "$line" | cut -d= -f1 | sed 's/^CONFIG_//')
 
-  # Reduction
-  # Unused features
+      echo "-$key" >> "$DEBUG_LOG"
+      scripts/config -d "$key"
+    done
+  }
+
+  disable_config_awk() {
+    local kconfig_file="$1"
+    local awk_pattern="$2"
+    local description="$3"
+    
+    if [ -z "$description" ]; then
+      echo "Error: Description is required for disable_config_awk" >&2
+      return 1
+    fi
+    
+    echo "======================================" >> "$DEBUG_LOG"
+    echo "Disabling: $description" >> "$DEBUG_LOG"
+    echo "======================================" >> "$DEBUG_LOG"
+    
+    awk "$awk_pattern" "$kconfig_file" | while IFS= read -r line; do
+      config=$(echo "$line" | cut -d= -f1 | sed 's/^config //')
+      
+      echo "-$config" >> "$DEBUG_LOG"
+      scripts/config -d "$config"
+    done
+  }
+
+  # TCP BBR
+  disable_config_pattern "TCP_CONG_.*"
+  disable_config_pattern "NET_SCH_.*"
+  scripts/config -e TCP_CONG_ADVANCED \
+            -e TCP_CONG_BBR \
+            -e DEFAULT_BBR \
+            -e NET_SCH_DEFAULT \
+            -e NET_SCH_FQ \
+            -e DEFAULT_FQ
+
+  # Expert option
+  scripts/config -e EXPERT \
+            -e PROCESSOR_SELECT
+  
+  # Kernel Configuration
+  ### Platform-specific, MUST EDIT
+  disable_config_pattern ".*(HYGON|CENTAUR|ZHAOXIN|STATS|QUOTA|DEBUG((_)?FS)?|DUMP|_DUMMY|TRACING|_(PCM)?TEST(ING)?|TABLET(S)?|TOUCHSCREEN)"
+  disable_config_pattern "(KEXEC|FIREWIRE|TINYDRM|VMWARE|IWL[0-9]|IPW|XIL).*"
+  disable_config_pattern ".*(VIA|NVIDIA|NFORCE|IBM|MLX|RAID|DEPRECATED|LEGACY|_(SIS|XIL|TI_)).*"
+  disable_config_pattern ".*((AFFS|BCACHEFS|BEFS|BTRFS|ECRYPT|EROFS|F2FS|JFFS2|UBIFS|GFS2|HFSPLUS|HFS|JFS|MINIX|NILFS2|OCFS2|OMFS|ORANGEFS|ROMFS|UFS|ZISOFS|ZONEFS)_FS)|(CEPH|CRAMFS|ZISOFS).*"
+  disable_config_pattern "(AIX|MAC|MINIX|SOLARIS_X86|LDM|KARMA)_(SUB)?PARTITION"
+  disable_config_pattern "(ATA_(OVER_ETH|SFF)|BT_(HCIBTUSB_(BCM|MTK|RTL)|HCI(UART|BCM.*)|MTK.*))"
+  disable_config_pattern "(BLK_DEV_(DRBD|FD|MD|NBD|NULL_BLK|RAM|RBD|UBLK|IO_TRACE)|DEBUG_(BOOT_PARAMS|WX|SHIRQ))"
+  disable_config_pattern "DRM_(AMDGPU_(CIK|SI)|AST|GMA500|MGAG200|NOUVEAU|RADEON|VBOXVIDEO|VMWGFX)"
+  disable_config_pattern "(INPUT_(JOY.*)|MEDIA_((ANALOG|DIGITAL)_TV|RADIO|TEST)_SUPPORT)"
+  disable_config_pattern "(IRQSOFF|PREEMPT|SCHED|HWLAT|OSNOISE|TIMERLAT|ATH5K|STACK)_TRACER"
+  disable_config_pattern "SECURITY_(SMACK|TOMOYO|LOADPIN|APPARMOR)"
+  disable_config_pattern "(VIDEO_(USBTV|TVAUDIO|MGB4|SOLO6X10|EM28XX|TW.*)|VGA_(ARB|SWITCHEROO))"
+
+  ### AC97
+  disable_config_awk "sound/pci/Kconfig" '
+    /^config / { config=$2; capture=0 }
+    /select SND_AC97_CODEC/ { capture=1 }
+    /^$/ { if (capture) print config; config=""; capture=0 }
+    END { if (capture) print config }
+  ' "AC97"
+
   scripts/config -d ACCESSIBILITY \
+            -d AGP \
+            -d ANDROID_BINDER_IPC \
+            -d ATM \
+            -d AUDIT \
+            -d BSD_DISKLABEL \
+            -d CAN \
+            -d CHROME_PLATFORMS \
+            -d CXL_BUS \
+            -d FDDI \
+            -d FPGA \
+            -d FUNCTION_ERROR_INJECTION \
+            -d GAMEPORT \
+            -d GNSS \
+            -d GOOGLE_FIRMWARE \
+            -d HAMRADIO \
             -d HIBERNATION \
+            -d HID_APPLE \
+            -d HYPERV \
+            -d INFINIBAND \
+            -d IPACK_BUS \
+            -d ISDN \
+            -d KFENCE \
+            -d MACINTOSH_DRIVERS \
+            -d MCB \
+            -d MELLANOX_PLATFORM \
+            -d MEMTEST \
+            -d MMIOTRACE \
+            -d MWAVE \
             -d NETWORK_FILESYSTEMS \
-            -d MEMORY_FAILURE \
-            -d ANDROID_BINDER_IPC
-            
-  # Unused devices
-  scripts/config -d USB_NET_AX8817X \
-              -d USB_NET_AX88179_178A \
-              -d USB_NET_NET1080 \
-              -d USB_NET_CDC_SUBSET \
-              -d USB_NET_ZAURUS \
-              -d SENSORS_SPD5118 \
-              -d USB_NET_CDC_NCM \
-              -d FUSION \
-              -d WLAN_VENDOR_ATMEL \
-              -d WLAN_VENDOR_BROADCOM \
-              -d WLAN_VENDOR_INTERSIL \
-              -d WLAN_VENDOR_MARVELL \
-              -d WLAN_VENDOR_MEDIATEK \
-              -d WLAN_VENDOR_MICROCHIP \
-              -d WLAN_VENDOR_PURELIFI \
-              -d WLAN_VENDOR_RALINK \
-              -d WLAN_VENDOR_REALTEK \
-              -d WLAN_VENDOR_RSI \
-              -d WLAN_VENDOR_SILABS \
-              -d WLAN_VENDOR_ST \
-              -d WLAN_VENDOR_TI \
-              -d WLAN_VENDOR_ZYDAS \
-              -d WLAN_VENDOR_QUANTENNA \
-              -d MEGARAID_NEWGEN \
-              -d INPUT_JOYDEV \
-              -d INPUT_JOYSTICK \
-              -d INPUT_TABLET \
-              -d INPUT_TOUCHSCREEN \
-              -d HID_APPLE
-
-  # Performance
-  scripts/config -d AUDIT \
-            -d FTRACE \
-            -d KEXEC \
-            -d KEXEC_FILE \
-            -d KPROBES \
+            -d NFC \
+            -d PARPORT \
+            -d PCCARD \
+            -d PHONET \
             -d PROC_KCORE \
             -d PROFILING \
-            -d SECURITY_APPARMOR \
-            -d SECURITY_LOADPIN \
-            -d SECURITY_LOCKDOWN_LSM \
-            -d SECURITY_SAFESETID \
-            -d SECURITY_LANDLOCK \
-            -d SECURITY_SMACK \
-            -d SECURITY_TOMOYO \
-            -d SECURITY_YAMA \
-            --set-str LSM "" \
-            -d WATCHDOG \
-            -d QUOTA \
-            -d XFS_QUOTA \
-            -d TMPFS_QUOTA \
-            -d ZSWAP \
-            -d BTRFS_FS \
-            -d HAMRADIO \
-            -d KFENCE \
-            -d SOFTLOCKUP_DETECTOR \
-            -d HARDLOCKUP_DETECTOR \
-            -d DETECT_HUNG_TASK \
-            -d SCHEDSTATS \
-            -d TASKSTATS \
-            -d IP_FIB_TRIE_STATS \
-            -d PAGE_POOL_STATS \
-            -d DMABUF_SYSFS_STATS \
-            -d XFS_ONLINE_SCRUB_STATS
-
-  # Platform-specific
-  scripts/config -d CHROME_PLATFORMS \
-            -d GOOGLE_FIRMWARE \
-            -d MACINTOSH_DRIVERS \
-            -d MELLANOX_PLATFORM \
-            -d SURFACE_PLATFORMS \
-            -d SOC_TI \
-            -d X86_PLATFORM_DRIVERS_DELL \
-            -d X86_PLATFORM_DRIVERS_HP
-
-  # Virtualisation
-  scripts/config -d XEN
-
-  # Legacy Hardware
-  scripts/config -d AGP \
-            -d ATA_SFF \
-            -d ISDN \
-            -d SERIAL_NONSTANDARD
-
-  # Bluetooth
-  scripts/config -d BT_HCIBTUSB_BCM \
-            -d BT_HCIBTUSB_RTL \
-            -d BT_HCIBTUSB_MTK
-
-  # DRM
-  scripts/config -d DRM_AMDGPU_CIK \
-            -d DRM_AMDGPU_SI
-
-  # Debugging
-  scripts/config -d PM_DEBUG \
-            -d ACPI_DEBUG \
-            -d PNP_DEBUG_MESSAGES \
-            -d DM_DEBUG \
-            -d ATH12K_DEBUG \
-            -d SND_DEBUG \
-            -d VIRTIO_DEBUG \
-            -d DYNAMIC_DEBUG \
-            -d DYNAMIC_DEBUG_CORE \
-            -d DEBUG_RODATA_TEST \
-            -d DEBUG_WX \
-            -d SHRINKER_DEBUG \
-            -d DEBUG_SHIRQ \
-            -d SCHED_DEBUG \
+            -d RC_CORE \
             -d RUNTIME_TESTING_MENU \
-            -d MEMTEST
+            -d SCSI_IPR_TRACE \
+            -d SIOX \
+            -d SLIMBUS \
+            -d SND_SOC_AC97_CODEC \
+            -d SURFACE_PLATFORMS \
+            -d TRACER_SNAPSHOT \
+            -d UPROBE_EVENTS \
+            -d USB_GADGET \
+            -d VBOXGUEST \
+            -d VMXNET3 \
+            -d WATCHDOG \
+            -d XEN \
+            -d ZSWAP
 
   ### Rewrite configuration
-  echo "Rewrite configuration..."
-  yes "" | make "${BUILD_FLAGS[@]}" prepare >/dev/null
-  yes "" | make "${BUILD_FLAGS[@]}" config >/dev/null
+  echo "Rewriting configuration..."
+  yes "" | make "${BUILD_FLAGS[@]}" prepare > debug_prepare.log 2>&1
+  yes "" | make "${BUILD_FLAGS[@]}" config > debug_config.log 2>&1
+  echo "Config rewritten"
 
   ### Prepared version
   make -s kernelrelease > version
@@ -492,9 +263,7 @@ _package() {
   pkgdesc="The $pkgdesc kernel and modules"
   depends=('coreutils' 'kmod' 'initramfs')
   optdepends=('wireless-regdb: to set the correct wireless channels of your country'
-              'linux-firmware: firmware images needed for some devices'
-              'modprobed-db: Keeps track of EVERY kernel module that has ever been probed - useful for those of us who make localmodconfig'
-              'scx-scheds: to use sched-ext schedulers')
+              'linux-firmware: firmware images needed for some devices')
   provides=(VIRTUALBOX-GUEST-MODULES WIREGUARD-MODULE KSMBD-MODULE UKSMD-BUILTIN NTSYNC-MODULE VHBA-MODULE ADIOS-MODULE)
 
   cd "$_srcname"
@@ -613,6 +382,7 @@ for _p in "${pkgname[@]}"; do
 done
 
 b2sums=('SKIP'
+        'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
